Fixed problems in spoiler function
camd67/moebot pull request #22
Opened 2018-01-18 19:09 UTC by Shadran

# This pull request changes the following things:

Improved spoiler text font, added error logging and retry on failed message deletion  
Fixed https://github.com/camd67/moebot/issues/21

## By submitting this Pull Request I agree to have done the following (check all that apply):

- [x] Run `go fmt` on all the files I've changed
- [x] Tested the bot on my own server to verify the feature works
- [x] Verified with CamD67 that the feature is desired (Check out the Projects page, or submit an issue for new features)
- [x] Submitted PR to the develop branch _not master!_

2018-01-20 20:42 UTC, camd67 requested changes

2018-01-20 20:42 UTC, camd67 commented on moebot_bot/util/gifmaker.go
> +var fontFace font.Face
Having a private package level variable to store this font face seems to not be necessary, since we're only using it in gif specific functions. 
More than that, I'd like the `util` package to be free of any state (with only a few minor exceptions like logging / debug info), especially not something so specific.
Perhaps we could pull the gif related stuff into a separate package specifically for them? `moebot_bot/util/gifs` with the `gifs` package? (or image would work too)

2018-01-20 20:58 UTC, Shadran commented on moebot_bot/util/gifmaker.go
> +var fontFace font.Face
I'm gonna change function signatures and just pass it down on gift creation then.  
Splitting the functions in another package seems good, but not necessary at the moment.

2018-01-21 16:30 UTC, Shadran commented on moebot_bot/util/gifmaker.go
> +var fontFace font.Face
Fixed with https://github.com/camd67/moebot/commit/24477971525ac2e89d04dc5d2d864e828db92698

2018-01-21 16:31 UTC, Shadran commented on moebot_bot/util/gifmaker.go
> +var fontFace font.Face
Fixed with https://github.com/camd67/moebot/commit/24477971525ac2e89d04dc5d2d864e828db92698

2018-01-21 22:45 UTC, camd67 approved these changes

2018-01-21 22:45 UTC, merged