Added timer command
camd67/moebot pull request #53
Opened 2018-06-14 05:56 UTC by efevans

# This pull request changes the following things:

Added a timer command for synchronizing time between users. Moderators can start (or restart) timers with `timer start`. All users can get the current timestamp with `timer`. Timers are unique by each channel.

I went with your implementation storing the timestamps for each channel, specifically stored in a map.

Let me know if you think steps for concurrency are warranted here. I didn't bother with it since I couldn't imagine a situation where a race condition would cause an issue.

Implements #52 

## By submitting this Pull Request I agree to have done the following (check all that apply):

- [x] Run `go fmt` on all the files I've changed
- [x] Tested the bot on my own server to verify the feature works
- [x] Verified with CamD67 that the feature is desired (Check out the Projects page, or submit an issue for new features)
- [x] Submitted PR to the develop branch _not master!_

2018-06-15 15:27 UTC, efevans commented
Golang detects for concurrent map read and write (or write and write) and causes a `fatal error: concurrent map read and map write`. 

https://golang.org/doc/go1.8#mapiter

I'll update the code to use sync.Mutex for concurrency.

2018-06-16 17:34 UTC, camd67 commented on moebot_bot/bot/commands/timer.go
> +		tc.chTimers.Lock()
For this one we can just do an `RLock` and `RUnlock` instead so it doesn't block other reads. `Lock` is only necessary when writing.

2018-06-16 17:41 UTC, camd67 requested changes

2018-06-16 17:41 UTC, camd67 commented on moebot_bot/bot/commands/timer.go
> +			pack.session.ChannelMessageSend(pack.message.ChannelID, "Timer started! OwO")
Ah  I see what you mean by emoticons now...

Unfortunately I'm going to request these removed. I'd prefer to keep moebot usable by any server, even those who aren't particularly into anime. While a lot of features are tailored to anime communities, a timer command certainly isn't.

All that being said, I just thought of the idea of having different "modes" you can switch on within moebot that use different strings for this kind of stuff... I'll add that as a separate feature

2018-06-16 17:41 UTC, camd67 commented
One big thing that this in-memory solution doesn't have is safety against crashes and reboots. All timers will be blown away if that happens. I'd prefer it to not happen very often, but it does happen occasionally.

This works for now, and when we update more of the infrastructure to be more easily reboot-able we should revisit this.

Still, looks good to me 👍

2018-06-16 19:42 UTC, camd67 approved these changes

2018-06-16 19:42 UTC, merged